appsody/docs

docs/getting-started/quick-start.md
Fixes review comments in PR #6
=> Quick start updates

docs/getting-started/installation.md, docs/using-appsody/building-and-deploying.md
Initial drop of build and deploy docs.
=> WIP - Build deploy

docs/architecture/controller.md, docs/architecture/mounts.md, docs/architecture/technical-overview.md, docs/overview.md
Merging controller and mounts into the technical overview
Adding metadata for rendering
=> docs: add metadata

STABLE_TECHNICAL_REQUIREMENTS.md
=> technical-requirement: add initial technical requirements

docs/stacks/stacks-overview.md
=> stacks-overview: add technical requirements

docs/stacks/creating-stacks.md, docs/stacks/modifying-stacks.md
=> stacks: removing empty docs

docs/overview.md
Next steps - fix TODO links for more information and add how does it work section
=> docs overview: Initial content

docs/getting-started/quick-start.md, docs/using-appsody/creating-project.md, docs/using-appsody/local-development.md
Signed-off-by: Kyle G. Christianson <christik@us.ibm.com>
=> Add content for using appsody docs

docs/using-appsody/building-and-deploying.md
- [x ] commit message follows [commit guidelines](https://github.com/appsody/docs/blob/master/CONTRIBUTING.md#commit-message-guidelines)
Fixes #issue-number
=> Initial change to the build docs for Chris PR

docs/getting-started/installation.md, docs/getting-started/quick-start.md, docs/stacks/create-or-modify.md, docs/stacks/stack-structure.md, docs/stacks/stacks-overview.md, docs/using-appsody/building-and-deploying.md, docs/using-appsody/creating-project.md, docs/using-appsody/local-development.md
=> docs: fix metadata

docs/architecture/technical-overview.md, docs/overview.md, docs/stacks/stacks-overview.md
=> docs: initial draft for how it works

CONTRIBUTING.md, README.md, docs/overview.md, docs/stacks/stacks-overview.md
=> links: add slack inviter links

docs/using-appsody/creating-project.md
Fix links to work on appsody.dev
- [x ] commit message follows [commit guidelines](https://github.com/appsody/docs/blob/master/CONTRIBUTING.md#commit-message-guidelines)
Fixes #issue-number
=> docs creating-a-project: change links to work on website

docs/getting-started/quick-start.md, docs/overview.md, docs/stacks/create-or-modify.md, docs/stacks/stack-structure.md, docs/stacks/stacks-overview.md
=> docs: remove relative paths

README.md
=> README: making readme's consistent across Appsody

docs/stacks/stack-structure.md
Fixes: https://github.com/appsody/docs/issues/46
=> docs: fix typo in stack-structure filename

docs/using-appsody/building-and-deploying.md
=> doc: fix typo in building-and-deploying

CONTRIBUTING.md
Fixes: https://github.com/appsody/docs/issues/41
=> contributing: fix broken links 

docs/stacks/create-or-modify.md
=> Fix stack structure link

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md
=> addressed changes

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
=> templates: create issue templates

.github/ISSUE_TEMPLATE/bug_report.md
=> issue-template: update template

docs/using-appsody/building-and-deploying.md, docs/using-appsody/installing-knative-locally.md
This adds documentation on how to set up a local Knative install using Kubernetes in Docker for Desktop and links to it from the deploying guide.
=> Knative local
